# Generated by Django 5.2.4 on 2025-07-05 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('symbol', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'symbols',
            },
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.BigIntegerField()),
                ('interval', models.BigIntegerField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('base_volume', models.FloatField()),
                ('usdt_volume', models.FloatField()),
                ('quote_volume', models.FloatField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.symbol')),
            ],
            options={
                'db_table': 'candles',
                'unique_together': {('open_time', 'symbol', 'interval')},
            },
        ),
    ]
