# Generated by Django 5.2.4 on 2025-07-05 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candle',
            options={'ordering': ['-open_time']},
        ),
    ]
