# Generated by Django 5.2.4 on 2025-09-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_alter_candle_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('trace', models.TextField(blank=True, null=True)),
                ('api_key', models.CharField(max_length=100)),
                ('secret_key', models.CharField(max_length=100)),
                ('api_passphrase', models.CharField(max_length=100)),
                ('timestamp_cursor', models.BigIntegerField(default=100)),
                ('is_position_active', models.BooleanField(default=False)),
                ('remote_id', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
