# Generated by Django 5.2.4 on 2025-09-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0003_positionmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionmanager',
            name='api_key',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='positionmanager',
            name='api_passphrase',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='positionmanager',
            name='secret_key',
            field=models.CharField(max_length=1000),
        ),
    ]
