# Generated by Django 5.2.4 on 2025-09-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0004_alter_positionmanager_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionmanager',
            name='sl_order_price',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
